<script type="text/javascript" src="${rc.contextPath }/js/iframe-custom.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/pandora-dialog.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/bblink-dialog.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/My97DatePicker/WdatePicker.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/newpanel.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/jquery.jsonSuggest.min.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/JQueryTooltip/js/jtip.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/JQueryValidate/jquery.validate.min.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/JQueryValidate/additional-methods.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/JQueryValidate/jquery.metadata.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/JQueryValidate/messages_zh.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/PCASelect/pcas.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/easyui/jquery.easyui.min.js" charset="utf-8"></script>
<script type="text/javascript" src="${rc.contextPath }/js/tableTop.js" charset="utf-8"></script>
<script type="text/javascript">var GLOBAL_CONTEXT = '${rc.contextPath}';</script>